version: '3'
services:
    openldap:
        image: osixia/openldap:latest
        ports:
            - "389:389"
#            - "636:636"
        volumes:
            - openldap-data:/var/lib/ldap
            - openldap-conf:/etc/ldap/slapd.d
        networks:
            - internal
    phpldapadmin:
        image: osixia/phpldapadmin:latest
        ports:
            - "3000:80"
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "openldap"
            PHPLDAPADMIN_HTTPS: "false"
        networks:
            - internal
    open-id-provider:
        build:
            context: open-id-provider-docker/
        ports:
            - "8000:8000"
        networks:
            - internal
        volumes:
            - openid-provider-data:/data

volumes:
    openldap-data:
    openldap-conf:
    openid-provider-data:

networks:
    internal: {}
